### ISSUE TITLE
what is the relationship between the smallest length, order and accuracy?

### ISSUE THREAD

**Issue by luckystarufo** [maroba/findiff#16]
In general, is there a way to determine the shortest length of a dimension if I want to apply an operator dk_dx = Findiff(dim, dx, k, acc=d)?

In other words, can k and d directly determine the shortest length required?

**Comment by maroba** [comment]
I assume, you mean the shortest length required for a given absolute accuracy on a given domain. That's not possible, because it strongly depends on the function you are sampling. In principle, the error can be estimated by the residual term in the Taylor expansion, which not only depends on the grid spacing, but also on the next higher derivative of the function.

**Comment by luckystarufo** [comment]
I see, thank you!
