### ISSUE TITLE
Non-uniform second-order first derivatives incorrect

### ISSUE THREAD

**Issue by ngaloppo** [maroba/findiff#90]
**Describe the bug**
Computing the second order first derivative of a simple 1D discrete function is incorrect

**To Reproduce**
Compare with `np.gradient()` with the following code:

```python
import numpy as np
from findiff import FinDiff

f = np.array([1, 2, 4, 7, 11, 16])
x = np.array([0., 1., 1.5, 3.5, 4., 6.])

d_dx = FinDiff(0, x, acc=2)
df_dx = d_dx(f)
print(f"{df_dx=}")

grad = np.gradient(f, x, edge_order=2)
print(f"{grad=}")
```
**Expected behavior**
I'm expecting the printed out values for `df_dx` and `grad` to be the same. Instead:

```
f=array([ 1,  2,  4,  7, 11, 16])
df_dx=array([ 0,  3,  3,  7,  6, -1])
grad=array([-1. ,  3. ,  3.5,  6.7,  6.9, -1.9])
```

I'm also a bit confused why the second order first derivatives are negative at the edges, for a clearly monotonically growing function. But that's where my math knowledge ends... 

**Desktop (please complete the following information):**
 - OS: macOS
 - Version `findiff==0.12.0`

**Comment by maroba** [comment]
Thanks for posting the issue. First of all, the fact that some values are negative although the function is monotonically increasing, is not a problem (same for np.gradient by the way). The reason is that in second order, the algorithm fits a second order polynomial at every grid point. And when you plot your function, you see that if you take the last three points and fit a parabola with yours eyes through them, it will have a negative slope there.

What worries me is that the results do not agree with np.gradient. I haven't looked at it thoroughly yet, but it seems hard to construct an example where this happens. Below is my code that runs 1000 different random samples, and in all cases, the results agree with np.gradient within a max. absolute relative error of 1E-12. I have to investigate some more...

```python
    np.random.seed(42)
    x_ends = np.logspace(0, 3, 20)

    counter = 0
    for x_end in x_ends:
        for _ in range(50):

            x = np.linspace(0, x_end, 10)
            f = np.sin(np.pi * x)
            x /= x[-1]

            indices_to_remove = np.random.choice(
                np.arange(len(x))[1:-1], size=4, replace=False
            )

            x = np.delete(x, indices_to_remove)
            f = np.delete(f, indices_to_remove)

            amp = 0.2
            noise = np.random.uniform(-amp, amp, size=x.shape)
            f += noise

            d_dx = FinDiff(0, x, acc=2)
            df_dx = d_dx(f)
            # print(f"{df_dx=}")

            grad = np.gradient(f, x, edge_order=2)

            err = np.max(abs((grad - df_dx) / grad))
            if err > 1e-12:
                raise AssertionError(f"{x_end=} {err=}")

            counter += 1

    print(f"Ran {counter} tests without deviation")
```

**Comment by ngaloppo** [comment]
Thanks for explaining the theory behind second order approximations. That makes sense. 

I'm not sure why your extensive test doesn't show the issue, since my single example clearly shows the issue. Perhaps it has to do with the fact that the samples are still integer (and multiples of each other) distances from each other in your test code?

**Comment by maroba** [comment]
Good hint! In fact, the problem was that `f = np.array([1, 2, 4, 7, 11, 16])` creates an ndarray with integer entries and when multiplying by floats, it absorbs the fractional part. Fixed it internally by implicitly converting to dtype=np.float64 in such cases. Just uploaded version 0.12.1 in PyPi.

**Comment by maroba** [comment]
Yes, for basic Python 3 ints/floats, you are right. But apparently, it’s a different behavior when you multiply a single float with a numpy array of ints. I wasn’t aware of this until now.
